# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import panzer_pb2 as panzer__pb2


class PanzerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Drive = channel.unary_unary(
        '/panzer.Panzer/Drive',
        request_serializer=panzer__pb2.DriveRequest.SerializeToString,
        response_deserializer=panzer__pb2.DriveResponse.FromString,
        )


class PanzerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Drive(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PanzerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Drive': grpc.unary_unary_rpc_method_handler(
          servicer.Drive,
          request_deserializer=panzer__pb2.DriveRequest.FromString,
          response_serializer=panzer__pb2.DriveResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'panzer.Panzer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
