# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import panzer_pb2 as panzer__pb2


class PanzerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Drive = channel.unary_unary(
        '/panzer.Panzer/Drive',
        request_serializer=panzer__pb2.DriveRequest.SerializeToString,
        response_deserializer=panzer__pb2.DriveResponse.FromString,
        )
    self.MoveTurret = channel.unary_unary(
        '/panzer.Panzer/MoveTurret',
        request_serializer=panzer__pb2.MoveTurretRequest.SerializeToString,
        response_deserializer=panzer__pb2.MoveTurretResponse.FromString,
        )
    self.Control = channel.unary_unary(
        '/panzer.Panzer/Control',
        request_serializer=panzer__pb2.ControlRequest.SerializeToString,
        response_deserializer=panzer__pb2.ControlResponse.FromString,
        )
    self.SendPing = channel.unary_unary(
        '/panzer.Panzer/SendPing',
        request_serializer=panzer__pb2.Ping.SerializeToString,
        response_deserializer=panzer__pb2.Pong.FromString,
        )


class PanzerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Drive(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MoveTurret(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Control(self, request, context):
    """Control components in bulk
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendPing(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PanzerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Drive': grpc.unary_unary_rpc_method_handler(
          servicer.Drive,
          request_deserializer=panzer__pb2.DriveRequest.FromString,
          response_serializer=panzer__pb2.DriveResponse.SerializeToString,
      ),
      'MoveTurret': grpc.unary_unary_rpc_method_handler(
          servicer.MoveTurret,
          request_deserializer=panzer__pb2.MoveTurretRequest.FromString,
          response_serializer=panzer__pb2.MoveTurretResponse.SerializeToString,
      ),
      'Control': grpc.unary_unary_rpc_method_handler(
          servicer.Control,
          request_deserializer=panzer__pb2.ControlRequest.FromString,
          response_serializer=panzer__pb2.ControlResponse.SerializeToString,
      ),
      'SendPing': grpc.unary_unary_rpc_method_handler(
          servicer.SendPing,
          request_deserializer=panzer__pb2.Ping.FromString,
          response_serializer=panzer__pb2.Pong.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'panzer.Panzer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
